#!/usr/bin/env node

var fs = require('fs'),
    path = require('path');
    
var configPath = path.resolve(__dirname, '../test/config.json'),
    configJson = require(configPath);
    
console.log(configJson);

